from typing import Iterable
from numbers import Number
import numpy as np
from scipy.optimize import least_squares, minimize
from .generate import generate_cc_ca_by_cccp
from ..basic import FitError
from ..util import _construct_param_vector, _construct_param_dict


def _residuals_for_fit_cc_by_cccp(params, ca_coords_obs, parse_dict, **kwargs):
    """
    Return the residuals between observed CA coordinates and those generated by CCCP coiled-coil parameters.

    Parameters
    ----------
    params : np.ndarray
        Flattened parameter vector.
    ca_coords_obs : np.ndarray
        Observed CA coordinates.
    parse_dict : dict
        Dictionary mapping parameter names to their indices or slices in the params vector.
    kwargs : dict
        Additional fixed parameters for coiled-coil generation.
    """

    param_kwargs = {}
    for key, value in parse_dict.items():
        param_kwargs[key] = params[value]
    pred_ca, _ = generate_cc_ca_by_cccp(**param_kwargs, **kwargs)
    return (pred_ca - ca_coords_obs).flatten()


def _scalar_for_fit_cc_by_cccp(params, ca_coords_obs: np.ndarray, parse_dict, **kwargs):
    """
    Return the scalar residual (RMSD) between observed CA coordinates and those generated by CCCP coiled-coil parameters.

    Parameters
    ----------
    params : np.ndarray
        Flattened parameter vector.
    ca_coords_obs : np.ndarray
        Observed CA coordinates.
    parse_dict : dict
        Dictionary mapping parameter names to their indices or slices in the params vector.
    kwargs : dict
        Additional fixed parameters for coiled-coil generation.
    """

    param_kwargs = {}
    for key, value in parse_dict.items():
        param_kwargs[key] = params[value]
    pred_ca, _ = generate_cc_ca_by_cccp(**param_kwargs, **kwargs)
    residuals = pred_ca - ca_coords_obs
    residuals = residuals.reshape((residuals.shape[0] * residuals.shape[1], 3))
    rmsd = np.sqrt(np.sum(residuals**2) / residuals.shape[0])
    return rmsd


def _optimize_cc_by_cccp(
    ca_coords_obs: np.ndarray, initial_params: dict, param_names_to_optimize: list
):
    """
    Single optimization step for fitting coiled-coil helices using CCCP parameters.

    Parameters
    ----------
    ca_coords_obs : np.ndarray
        Observed CA coordinates.
    initial_params : dict
        Initial parameters for optimization.
    param_names_to_optimize : list
        List of parameter names to optimize.

    Returns
    -------
    final_params : dict
        Optimized parameters after fitting.
    result : OptimizeResult
        Result object from the optimization process.
    """

    for key in ["helix_num", "residue_num", "senses"]:
        if key not in initial_params:
            raise ValueError(f"initial_params must include '{key}' for optimization.")
        if key in param_names_to_optimize:
            raise ValueError(f"'{key}' cannot be optimized and must be fixed.")

    # Boundary conditions for parameters
    lb_params = dict(
        centroid=(-np.inf, -np.inf, -np.inf),
        z=(-1.0, -1.0, -1.0),
        r0=3.6,
        w0=-np.pi,
        phi0=-np.inf,
        r1s=[2.2] * initial_params["helix_num"],
        w1s=[np.deg2rad(90)] * initial_params["helix_num"],
        phi1s=[-np.inf] * initial_params["helix_num"],
        pitch_angles=[-np.pi / 2] * initial_params["helix_num"],
        dphi0s=[0] * initial_params["helix_num"],
        z_offsets=[-np.inf] * initial_params["helix_num"],
    )
    ub_params = dict(
        centroid=(np.inf, np.inf, np.inf),
        z=(1.0, 1.0, 1.0),
        r0=np.inf,
        w0=np.inf,
        phi0=np.inf,
        r1s=[2.4] * initial_params["helix_num"],
        w1s=[np.deg2rad(110)] * initial_params["helix_num"],
        phi1s=[np.inf] * initial_params["helix_num"],
        pitch_angles=[np.pi / 2] * initial_params["helix_num"],
        dphi0s=[2 * np.pi] * initial_params["helix_num"],
        z_offsets=[np.inf] * initial_params["helix_num"],
    )

    # Prepare parameter vectors and bounds
    p0, parse_dict = _construct_param_vector(initial_params, param_names_to_optimize)
    lb, parse_dict_lb = _construct_param_vector(lb_params, param_names_to_optimize)
    ub, parse_dict_ub = _construct_param_vector(ub_params, param_names_to_optimize)
    assert len(p0) == len(lb) == len(ub), (
        "Parameter and bound lengths do not match. Check information below\n"
        f"p0 length: {len(p0)}\n"
        f"lb length: {len(lb)}\n"
        f"ub length: {len(ub)}\n"
        f"parse_dict: {parse_dict}\n"
        f"parse_dict_lb: {parse_dict_lb}\n"
        f"parse_dict_ub: {parse_dict_ub}\n"
    )

    # Perform optimization
    fixed_params = initial_params.copy()
    for name in param_names_to_optimize:
        fixed_params.pop(name, None)
    result = minimize(
        lambda x: _scalar_for_fit_cc_by_cccp(
            x, ca_coords_obs, parse_dict=parse_dict, **fixed_params
        ),
        p0,
        bounds=list(zip(lb, ub)),
        method="L-BFGS-B",
        options={"maxiter": 100000, "maxfun": 100000},
        tol=1e-6,
    )
    if not result.success:
        raise FitError(
            "Coiled-coil helix fitting failed with message:\n" + result.message
        )

    # Annotate optimized parameters
    params = result.x
    optimized_params = _construct_param_dict(params, parse_dict)
    optimized_params.update(fixed_params)
    optimized_params["z"] /= np.linalg.norm(optimized_params["z"])

    return optimized_params, result


def _guess_senses(ca_coords_obs):
    """
    Parameters
    ----------
    ca_coords_obs : np.ndarray
        Observed CA coordinates with shape (helix_num, residue_num, 3).

    Returns
    -------
    senses : list
        List of senses (+1 or -1) for each helix. +1 indicates the helix direction aligns with the first helix, -1 indicates opposite direction.
    """

    helix_num = ca_coords_obs.shape[0]
    directions_approx = []
    for i in range(0, helix_num):
        directions_approx.append(ca_coords_obs[i, -1] - ca_coords_obs[i, 0])
    senses = [1]
    for i in range(1, helix_num):
        if np.dot(directions_approx[i], directions_approx[0]) < 0:
            senses.append(-1)
        else:
            senses.append(1)
    senses = np.array(senses)
    return senses


def _guess_direction(ca_coords_obs, senses):
    """
    Returns
    -------
    direction : np.ndarray
        The guessed direction vector of the coiled-coil structure (normalized).
    """
    helix_num = ca_coords_obs.shape[0]
    directions_with_senses = np.vstack(
        [
            ca_coords_obs[i, -1] - ca_coords_obs[i, 0] * senses[i]
            for i in range(helix_num)
        ]
    )
    direction = np.mean(directions_with_senses, axis=0)
    direction /= np.linalg.norm(direction)
    return direction


def _exclude_params(param_names: list, params_to_exclude: list):
    return [name for name in param_names if name not in params_to_exclude]


def _angle_pi_mod(angle):
    """Modulate angle to be within [-pi, pi]."""
    angle = np.mod(angle + np.pi, 2 * np.pi) - np.pi
    return angle


def fit_cc_by_cccp(
    ca_coords_obs: np.ndarray,
    helix_num: int = None,
    residue_num: int = None,
    senses: Iterable[int] = None,
    centroid: Iterable[float] = None,
    y_prototype: Iterable[float] = None,
    z: Iterable[float] = None,
    r0: float = None,
    w0: float = None,
    phi0: float = 0.0,
    dphi0s: float = None,
    r1s: Iterable[float] | float = 2.26,
    w1s: Iterable[float] | float = 4 * np.pi / 7,
    phi1s: Iterable[float] | float = 0.0,
    pitch_angles: Iterable[float] | float = -0.2096,
    z_offsets: Iterable[float] | float = 0,
    params_not_to_fit: list[str] = [],
):
    """
    Parameters
    ----------
    ca_coords_obs : np.ndarray
        Observed CA coordinates with shape (helix_num, residue_num, 3).
    initial_params : dict
        Initial parameters for coiled-coil fitting.

    Returns
    -------
    params : dict
        Fitted parameters of the coiled-coil helix.
    """

    # Guess initial parameters if not provided
    initial_params = {}
    # Suggested parameters for different helix numbers
    # r0 = 2.4 + 1.24 * helix_num
    # w0 = -14.52 / (helix_num + 1.936) (in degrees per residue)
    # See: Probing Designability via a Generalized Model of Helical Bundle Geometry
    helix_num = helix_num if helix_num is not None else ca_coords_obs.shape[0]
    initial_params["helix_num"] = helix_num
    residue_num = residue_num if residue_num is not None else ca_coords_obs.shape[1]
    initial_params["residue_num"] = residue_num
    senses = senses if senses is not None else _guess_senses(ca_coords_obs)
    initial_params["senses"] = senses
    centroid = (
        np.array(centroid)
        if centroid is not None
        else np.mean(ca_coords_obs, axis=(0, 1))
    )
    initial_params["centroid"] = centroid
    z = (
        np.array(z)
        if z is not None
        else _guess_direction(
            ca_coords_obs=ca_coords_obs, senses=initial_params["senses"]
        )
    )
    helix_1_centroid = np.mean(ca_coords_obs[0], axis=0)
    y_prototype = helix_1_centroid - initial_params["centroid"]
    initial_params["y_prototype"] = y_prototype
    initial_params["z"] = z

    r0 = r0 if r0 is not None else 2.4 + 1.24 * initial_params["helix_num"]
    initial_params["r0"] = r0
    w0 = (
        w0
        if w0 is not None
        else 1.51 * np.sin(-0.2096) / (2.4 + 1.24 * initial_params["helix_num"])
    )
    initial_params["w0"] = w0
    initial_params["phi0"] = phi0
    initial_params["dphi0s"] = (
        np.array(dphi0s)
        if dphi0s is not None
        else np.linspace(0, 2 * np.pi, initial_params["helix_num"], endpoint=False)
    )
    assert (
        len(initial_params["dphi0s"]) == initial_params["helix_num"]
    ), "Length of dphi0s must match helix_num"
    for key, value in zip(
        ["r1s", "w1s", "phi1s", "pitch_angles", "z_offsets"],
        [r1s, w1s, phi1s, pitch_angles, z_offsets],
    ):
        if isinstance(value, Number):
            initial_params[key] = np.ones(shape=(helix_num)) * value
        else:
            initial_params[key] = value
        assert (
            len(initial_params[key]) == initial_params["helix_num"]
        ), f"Length of {key} must match helix_num"

    # Optimize parameters step by step
    params_to_optimize = ["centroid"]
    stage_params, result = _optimize_cc_by_cccp(
        ca_coords_obs=ca_coords_obs,
        initial_params=initial_params,
        param_names_to_optimize=_exclude_params(params_to_optimize, params_not_to_fit),
    )

    for _ in range(10):

        stage_params["phi0"] = _angle_pi_mod(stage_params["phi0"])
        stage_params["phi1s"] = _angle_pi_mod(stage_params["phi1s"])
        stage_params["centroid"] += (
            np.mean(stage_params["z_offsets"] * stage_params["senses"])
            * stage_params["z"]
        )
        stage_params["z_offsets"] -= stage_params["senses"] * np.mean(
            stage_params["z_offsets"] * stage_params["senses"]
        )

        params_to_optimize = [
            "dphi0s",
            "phi1s",
            "z_offsets",
        ]
        stage_params, result = _optimize_cc_by_cccp(
            ca_coords_obs=ca_coords_obs,
            initial_params=stage_params,
            param_names_to_optimize=_exclude_params(
                params_to_optimize, params_not_to_fit
            ),
        )

        param_names_to_optimize = [
            "r0",
            "w0",
            "phi0",
        ]
        stage_params, result = _optimize_cc_by_cccp(
            ca_coords_obs=ca_coords_obs,
            initial_params=stage_params,
            param_names_to_optimize=_exclude_params(
                param_names_to_optimize, params_not_to_fit
            ),
        )

        param_names_to_optimize = [
            "centroid",
            "z",
            "r0",
            "w0",
            "phi0",
            "dphi0s",
            "r1s",
            "w1s",
            "phi1s",
            "pitch_angles",
            "z_offsets",
        ]
        stage_params, result = _optimize_cc_by_cccp(
            ca_coords_obs=ca_coords_obs,
            initial_params=stage_params,
            param_names_to_optimize=_exclude_params(
                param_names_to_optimize, params_not_to_fit
            ),
        )

    rmsd = np.sqrt(np.sum(result.fun**2) / (helix_num * residue_num))
    xyz, params = generate_cc_ca_by_cccp(**stage_params)
    return params, rmsd, xyz
